import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "!./src/components/configurator/ModelStage.tsx",
  ],
  safelist: [
    "relative",
    "overflow-hidden",
    "rounded-[2rem]",
    "border",
    "border-white/10",
    "bg-moss",
    "shadow-soft",
    "absolute",
    "inset-0",
    "flex",
    "items-center",
    "justify-between",
    "border-b",
    "px-6",
    "py-5",
    "py-4",
    "text-xs",
    "font-black",
    "uppercase",
    "tracking-[0.24em]",
    "text-orange",
    "mt-2",
    "text-xl",
    "tracking-[-0.03em]",
    "text-white",
    "rounded-full",
    "bg-white/10",
    "px-3",
    "py-1",
    "tracking-[0.18em]",
    "text-white/40",
    "text-sm",
    "font-semibold",
    "text-white/60",
    "grid",
    "grid-cols-2",
    "gap-2",
    "rounded-2xl",
    "bg-white/[0.08]",
    "p-1",
    "rounded-xl",
    "px-4",
    "py-2",
    "transition",
    "bg-orange",
    "text-white/65",
    "hover:bg-white/10",
    "hover:text-white",
    "h-[360px]",
    "w-full",
    "md:h-[480px]",
    "border-t",
    "leading-6",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#111812",
        paper: "#f4efe6",
        ink: "#f7f3ea",
        charcoal: "#3f4238",
        moss: "#222c24",
        olive: "#4a4b40",
        orange: "#f79300",
        green: "#65b32e",
        sand: "#d8cbbb",
      },
      boxShadow: {
        soft: "0 28px 80px rgba(0, 0, 0, 0.28)",
        card: "0 16px 40px rgba(0, 0, 0, 0.18)",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      backgroundImage: {
        "stage-glow":
          "radial-gradient(circle at top, rgba(249, 136, 1, 0.18), transparent 42%), radial-gradient(circle at bottom right, rgba(101, 179, 46, 0.18), transparent 35%)",
      },
      fontFamily: {
        sans: ["Montserrat", "Aptos", "Segoe UI", "Helvetica Neue", "sans-serif"],
        display: ["Montserrat", "Aptos Display", "Segoe UI", "Helvetica Neue", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
